# ============================================================================
# WARNING: AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY!
# ============================================================================
# This file is automatically generated by client_tools/client_generator.py
# Any manual changes will be overwritten when the generator runs again.
#
# To update this file:
#   1. Modify the source files in src/twinkle/
#   2. Run: python client_tools/client_generator.py
# ============================================================================

from typing import List

from twinkle.data_format import Trajectory
from twinkle_client.http import TWINKLE_SERVER_URL, heartbeat_manager, http_post


class MathReward:
    """Client wrapper for MathReward that calls server HTTP endpoints."""

    def __init__(self, ground_truth_key: str = 'solution'):
        from twinkle_client.http import get_base_url
        self.server_url = get_base_url()

        response = http_post(
            url=f'{self.server_url}/processors/create',
            json_data={
                'processor_type': 'reward',
                'class_type': 'MathReward',
                **{
                    'ground_truth_key': ground_truth_key
                }
            })
        response.raise_for_status()
        self.processor_id = response.json()['processor_id']
        heartbeat_manager.register_processor(self.processor_id)

    def __del__(self):
        try:
            heartbeat_manager.unregister_processor(self.processor_id)
        except:
            pass

    def __call__(self, trajectories: List[Trajectory], ground_truths: List[Trajectory]):
        response = http_post(
            url=f'{self.server_url}/processors/call',
            json_data={
                'processor_id': self.processor_id,
                'function': '__call__',
                **{
                    'trajectories': trajectories,
                    'ground_truths': ground_truths
                },
            })
        response.raise_for_status()
        return response.json()['result']
