# ============================================================================
# WARNING: AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY!
# ============================================================================
# This file is automatically generated by client_tools/client_generator.py
# Any manual changes will be overwritten when the generator runs again.
#
# To update this file:
#   1. Modify the source files in src/twinkle/
#   2. Run: python client_tools/client_generator.py
# ============================================================================

from typing import Callable, Type, Union
from twinkle_client.http import http_post, heartbeat_manager
from twinkle.dataset import Dataset
from twinkle.processor import InputProcessor

class DataLoader(object):
    """Client wrapper for DataLoader that calls server HTTP endpoints."""

    def __init__(self, dataset: Union[Dataset, Callable], **kwargs):
        from twinkle_client.http import get_base_url
        self.server_url = get_base_url()

        response = http_post(
            url=f'{self.server_url}/processors/create',
            json_data={
                'processor_type': 'dataloader',
                'class_type': 'DataLoader',
                **{'dataset': dataset}, **kwargs
            }
        )
        response.raise_for_status()
        self.processor_id = response.json()['processor_id']
        heartbeat_manager.register_processor(self.processor_id)

    def __del__(self):
        try:
            heartbeat_manager.unregister_processor(self.processor_id)
        except:
            pass

    
    def __len__(self):
        response = http_post(
            url=f'{self.server_url}/processors/call',
            json_data={
                'processor_id': self.processor_id,
                'function': '__len__',
                **{},
            }
        )
        response.raise_for_status()
        return response.json()["result"]
    

    def set_processor(self, processor_cls: Union[Type[InputProcessor], str, InputProcessor, Callable], **kwargs):
        response = http_post(
            url=f'{self.server_url}/processors/call',
            json_data={
                'processor_id': self.processor_id,
                'function': 'set_processor',
                **{'processor_cls': processor_cls},
                **kwargs
            }
        )
        response.raise_for_status()
        return response.json()["result"]
    

    def __iter__(self):
        response = http_post(
            url=f'{self.server_url}/processors/call',
            json_data={
                'processor_id': self.processor_id,
                'function': '__iter__',
                **{},
            }
        )
        response.raise_for_status()
        return self
    
    def __next__(self):
        response = http_post(
            url=f'{self.server_url}/processors/call',
            json_data={
                'processor_id': self.processor_id,
                'function': '__next__',
            }
        )
        response.raise_for_status()
        return response.json()["result"]
    